version: 2.1
orbs:
  node: circleci/node@1.1
  jobs:
     test:
       steps:
         - checkout
         - node/install-packages
         - run:
           name: Run test/report
           command: npm run report
